server:
    port: 8099
#spring
spring:
  #配置ES
  data:
    elasticsearch:
      cluster-name: es-cn-v0h0khx5t001m74j9
      cluster-nodes: 120.27.228.1:9200
      #是否本地连接
      local: false
      repositories:
        enabled: true

  #DATABASE 主数据源 默认
  datasource:
    url: jdbc:mysql://211.95.56.10:3307/wu_test
    username: testdb
    password: testhuadongmedia123
    driver-class-name: com.mysql.jdbc.Driver
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    type: com.alibaba.druid.pool.DruidDataSource
  #配置redis
  redis:
    database: 1
    host: 127.0.0.1
    port: 6379
    password: 123456
    pool:
      max-wait: 0
      max-idle: 8
      min-idle: 0
      max-active: 8
    timeout: 2000
#配置mybatis
mybatis:
  typeAliasesPackage: com.huadongmedia.entity
  mapperLocations: classpath:mybatis/*.xml

#更多数据源
custom:
  datasource:
    names: ds1,ds2,ds3
    ds1:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://211.95.56.10:3307/wu_test
      username: testdb
      password: testhuadongmedia123